package uz.career.career_bot.enums;

public enum BotState {
    START,
    ENTER_NAME,
    SELECT_CATEGORY,
    SELECT_PROFESSION,
    SELECT_SKILLS,
    SELECT_EXPERIENCE,
    SELECT_LOCATION,
    ENTER_SALARY,

    USER_MAIN_MENU,

    ENTER_COMPANY_NAME,
    ENTER_COMPANY_INN,
    SELECT_INDUSTRY,
    ENTER_COMPANY_CONTACT,
    COMPANY_PENDING,

    HR_MAIN_MENU,
    ADD_JOB_TITLE,
    ADD_JOB_DESCRIPTION,
    ADD_JOB_CATEGORY,
    ADD_JOB_PROFESSION,
    ADD_JOB_SKILLS,
    ADD_JOB_EXPERIENCE,
    ADD_JOB_SALARY,
    ADD_JOB_LOCATION,
    ADD_JOB_TYPE,

    EDIT_NAME,
    EDIT_CATEGORY,
    EDIT_PROFESSION,
    EDIT_SKILLS,
    EDIT_EXPERIENCE,
    EDIT_LOCATION,
    EDIT_SALARY,
    EDIT_CONTACT,
    EDIT_CV,

    UPLOAD_CV,
}